### ISSUE TITLE
Complete restructuring of the client

### ISSUE THREAD

**Issue by rafaelschlatter** [RaaLabs/TSIClient#37]
This is more of a proposal than a issue, im thinking of a restructuring of the TSIClient. Currently, the client and all its method are in one big file. We could split the client into different files and classes, each dealing with one specific part of the TSI apis. Each class has similar methods to interact with whatever its dealing with. I havent thought it all through yet, but maybe something like this:

- `TSIClient.hierarchies.get()`
- `TSIClient.hierarchies.update()`
- `TSIClient.hierarchies.delete()`,

and likewise for types, instances, and query. This would make the TSIClient more similar to the underlying api and probably more intuitive to use for somebody who is already familiar with the Microsoft apis. I think its also a bit nicer to split the code as it is growing (currently the TSIClient has a subset of the functionality of the api, and we might want/need to extend the TSIClient in the future). It would also make collaboration easier, since not everybody is editing the same file. But it would be a **breaking change**, and it might not be worth the effort if we can continue using the client as we do today.

What do you think? @srudaa @SiriOvregard @maikberthelsen

**Comment by SiriOvregard** [comment]
I think it's a very good suggestion. I know @maikberthelsen has been working on implementing the new Gen2 payload functionality, but now sure if she has looked into restructuring.

**Comment by maikberthelsen** [comment]
I think it would be very useful. I have not worked with the Microsoft apis before, but it seems like the TSIClient could be more intuitive than what it is now. As Siri said I am working some with the client now but have only implemented some minor functionality-improvements, so I am not really familiar with the complete capability of the client.

**Comment by srudaa** [comment]
Yes, we should break the code out in smaller parts. I think it is worth creating a breaking change for this.

**Comment by rafaelschlatter** [comment]
Closed by PR #40.
