### ISSUE TITLE
Implement new aggregation functions that came with Gen2

### ISSUE THREAD

**Issue by maikberthelsen** [RaaLabs/TSIClient#38]

**Comment by rafaelschlatter** [comment]
@maikberthelsen Can this issue be closed?

**Comment by maikberthelsen** [comment]
Yes, I thought it would close automatically when I added it to the previous PR but guess not.

**Comment by rafaelschlatter** [comment]
Thanks. I think it only closes automatically if one of your commit messages in that PR contains "close #38". Note exactly sure of the syntax.
